#-------------------------------
# General Site Settings
title: Eunki Cho
logo: cekkec95_icon.png # You can add own logo.
# description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Eunki Cho
  image: cekkec95.jpg
  say-hello: Hello, I’m <strong>Eunki Cho</strong>
  bio: "I’m currently pursuing a Ph.D. in <strong><span style='color: #6B46C1;'>Artificial Intelligence</span></strong> at <strong><span style='color: #3182CE;'>Kyung Hee University</span></strong>, affiliated with the <strong><span style='color: #38A169;'>Augmented Intelligence (AMI) Laboratory</span></strong> under the supervision of Prof. <strong>Seong-Tae Kim</strong>. My primary research interests include <strong>segmentation</strong> and <strong>generative modeling</strong> in <strong>computer vision</strong>, <strong>medical imaging</strong>, and <strong>remote sensing</strong>."
  # Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
